### ISSUE TITLE
me saca del juego

### ISSUE THREAD

**Issue by FuzzyGrim** [TranScene/Danganronpa-2#10]
Al principio del capitulo 2 creo, me saca del juego constantemente diciendo que el juego dejó de funciona. Concretamente cuando SPOILER ALERTA

nose si es en el cap 2 pero es cuando hiyoko saionji hace el decorado para recordar a la fotografa y despues aparece megumi y se va. Despues de eso deja de funcionar

**Comment by Darkmet98** [comment]
¿Como que aparece Megumi? O.o

**Comment by FuzzyGrim** [comment]
Monomi xD me equivoqué, no se porque pensaba que se llamaba así...

**Comment by Darkmet98** [comment]
Puedes grabar el error?

**Comment by joguersan** [comment]
Tras 10 días sin dar una causa clara del error, procedo a cerrar la issue
