### ISSUE TITLE
Fallos de texto?

### ISSUE THREAD

**Issue by Roma1417** [TranScene/Danganronpa-2#11]
Hola, en primer lugar queria agradecer el trabajo realizado, en terminos generales esta muy bien logrado desde las traducciones hasta las ediciones graficas, espero que pronto salga a la luz el proyecto de parche para Danganronpa V3, sigan asi!

Por otra parte, queria aportar con dos pequeños errores que encontre:
El primero es el el quinto juicio, en inmersión lógica.
![20171225061113_1](https://user-images.githubusercontent.com/34905118/34400576-9ebea034-eb71-11e7-9461-467b4f4b79b7.jpg)
Preguntaba en que estado deberia estar el veneno, las opciones son: Solido, liquido y gas.
Creo que este error seria mas gramatical que ortografico, ya que gas es un sustantivo y el estado deberia ser "gaseoso" en ese caso (No se si en otros paises será valido)

El segundo error es en el ultimo juicio, cuando Hinata se confronta con sus otros yo.
![20171227011653_1](https://user-images.githubusercontent.com/34905118/34400601-f09d73b2-eb71-11e7-8b50-45a0964712dc.jpg)
El "a" que esta entre "traiciono" y "la" esta de mas, la oración debería ser "Hasta me traiciono la academia que mas admiraba"

Mas allá de eso el trabajo esta re bien logrado, congratulations!

**Comment by joguersan** [comment]
Fallos corregidos, muchas gracias por tu ayuda. Procedo a cerrar la issue
