### ISSUE TITLE
problema con el parche

### ISSUE THREAD

**Issue by caketria** [TranScene/Danganronpa-2#12]
Hola disculpa cuando intento parchear en el juego me sale esto también estoy confundida que debo hacer???
![pito](https://user-images.githubusercontent.com/34930813/34429606-0f6fba44-ec20-11e7-8b92-a278af5ef661.png)
y cuando selecciono una carpeta me sale que mi carpeta no es valida, que tengo que tener instalado Danganronpa 2 previamente instalado es su versión original de Steam

**Comment by joguersan** [comment]
Tienes que seleccionar la carpeta donde se ha instalado Danganronpa 2, no una cualquiera. Si no lo has comprado en Steam no podemos ayudarte a identificar la carpeta de instalación, tendrás que arreglártelas por tu cuenta.
