### ISSUE TITLE
Los comandos no van

### ISSUE THREAD

**Issue by lisett23543532** [TranScene/Danganronpa-2#13]
Entoces en la confratacion refutadora si no tengo presionado ctrl non dispara lo deberia de disparar y después de haber disparado a todo lo que tenia y hace empezar de nuevo,ya lo hice muchas veces y me cansando de repetir siempre,y es ya la 2 vez que lo hace,me esta haciendo enojar,si sigue asi no puedo avanzar.

**Comment by joguersan** [comment]
Por favor explícate de una forma más coherente o no podremos identificar el error.

**Comment by lisett23543532** [comment]
Aunque hago lo que se tiene que hacer,disparando a todos las frases,nunca
avanza,desde el capitulo 3 vino este problema,primero teniendo presionado
"ctrl" iba,ahora no se que hacer para poder ir adelante.quisiera poner una
imagen pero ahora cuando intento hacerlo se para el ordenador,y cuando van
a poner la version para psp?

2017-12-29 18:43 GMT+01:00 joguersan <notifications@github.com>:

**Comment by Darkmet98** [comment]
@lisett23543532 
1º transcene entera está harto de repetir hasta la saciedad, NO vamos a portearlo a la PSP.
2º eso es problema del juego, no de la traducción.
3º parece ser problema de tu PC

**Comment by lisett23543532** [comment]
solucione el problema de la imagen,es aqui que se queda

2017-12-29 19:26 GMT+01:00 Darkmet <notifications@github.com>:

**Comment by lisett23543532** [comment]
Pude solucionarlo sola

2017-12-29 20:11 GMT+01:00 K-pop & Drama Iloveyou <lisett1597@gmail.com>:
