### ISSUE TITLE
tengo un problema

### ISSUE THREAD

**Issue by finnlol24** [TranScene/Danganronpa-2#15]
cuando lo parcheo y me sale eso. busco la carpeta y lo parcheo normalmente. pero cuando abro el juego se ve en ingles y no en español.

que puedo hacer

**Comment by Darkmet98** [comment]
¿Has leido las instrucciones que salen en el botón «Leeme» del programa?

**Comment by finnlol24** [comment]
si. pero no me funciona

**Comment by joguersan** [comment]
¿También la parte que dice que hay que seleccionar la opción "Keyboard and Mouse" en el launcher del juego?

**Comment by Darkmet98** [comment]
¿Ejecutas el juego con lo la opción del teclado o con el del gamepad?

**Comment by finnlol24** [comment]
la opcion del teclado y raton

**Comment by joguersan** [comment]
¿Y el parcheador al terminar te dice que se ha instalado correctamente y que no ha habido ningún problema? Debo suponer que estás usando windows

**Comment by finnlol24** [comment]
uso windows pero si me sale error. 

Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.UnauthorizedAccessException: Acceso denegado a la ruta de acceso 'C:\Program Files (x86)\Danganronpa 2 Goodbye Despair\dr2_data_keyboard.wad'.
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.File.InternalDelete(String path, Boolean checkHost)
   en DR2_traduccion.Form1.<pictureBox1_Click>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.2600.0 built by: NET471REL1LAST
    Código base: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Danganronpa_2_Español_[Transcene]
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 1.0.0.0
    Código base: file:///C:/Users/Elizabeth/Desktop/Danganronpa_2_Espanol_.Transcene%20(1).exe
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.2556.0 built by: NET471REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.2556.0 built by: NET471REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.2556.0 built by: NET471REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.2556.0 built by: NET471REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.2600.0 built by: NET471REL1LAST
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.2556.0 built by: NET471REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.2556.0 built by: NET471REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.2556.0 built by: NET471REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.2556.0 built by: NET471REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.


eso me sale

**Comment by joguersan** [comment]
Tienes que ejecutar el parcheador como administrador

**Comment by finnlol24** [comment]
muchas gracias. hay me funciono. enserio se los agradesco por ayudarme y por tomarse la molestia de traducir este grandioso juego

**Comment by Darkmet98** [comment]
Cierro la issue ya que el problema está solucionado.
