### ISSUE TITLE
¿Error de traducción? - Munición, CASO 1

### ISSUE THREAD

**Issue by manudebroco** [TranScene/Danganronpa-2#16]
¡Hola! Creo que hay un error en la traducción de una de las pistas del primer juicio. El texto es el siguiente:

![testimonio](https://user-images.githubusercontent.com/35060930/34517678-4d3b13f4-f07c-11e7-9df8-1e5a2835ab11.jpg)

Según te cuenta la propia Nanami, mientras hacía guardia en la puerta del edificio Kuzuryuu se pasó por allí, habló con ella y se fue. Kuzuryuu nunca llegó a entrar en el edificio viejo, así que tampoco pudo salir de el.

Al repasar las pistas antes del juicio me di cuenta de que no me tenía sentido, así que busque un gameplay en inglés para comparar. Allí decía: "When Chiaki was standing guard outside, Fuyuhiko apparently came to the old bulding, then walked away".

Es decir, en lugar de "salió del edificio viejo" debería ser que "se acercó al edificio viejo", o algo así.

¡Saludos!

**Comment by joguersan** [comment]
Efectivamente, era un error que teníamos ya corregido, pero por alguna razón no acabó incluido en la última revisión. Gracias por tu ayuda, procedo a cerrar la issue.
