### ISSUE TITLE
Regalos

### ISSUE THREAD

**Issue by Alexfirer** [TranScene/Danganronpa-2#17]
Por algun motivo en el nuevo parche,no puedo darle regalos ni a mi mascota, ni a los estudiantes definitivos, quedando esa opcion inutilizable (con el teclado o el control), actualmente uso un control de PS3 con scp service para simularlo como uno de Xbox 360.

**Comment by Darkmet98** [comment]
¿Puedes explicar mejor el problema y los pasos que realizas para darle los regalos?

**Comment by Alexfirer** [comment]
Primero que nada,ando en el tiempo libre,me acerco a uno de los
personajes,en este caso nanami y paso el rato con ella,luego me presenta la
opción de darle el regalo,acepto y cuando busco en la lista de los regalos
y presiono la y (en mi control) no hace nada,verifique con el teclado y
tampoco hace nada,lo mismo pasa con la mascota.

**Comment by joguersan** [comment]
¿En el teclado qué tecla pulsas? Debes presionar el tabulador. Porque acabo de comprobarlo y me funcionan tanto el teclado como el mando original de XBOX One. Puede que tengas el SCPServer mal configurado y no pulsaras la tecla adecuada del teclado.

**Comment by Alexfirer** [comment]
Verifique en otras partes del juego la y,por ejemplo en los debates
continuos y funciona,dispara la munición sin problemas,solo me pasa con los
regalos,tb funciona la y para ver todas las pistas, el problema es con los
regalos

**Comment by Darkmet98** [comment]
prueba a desactivar el SCPServer e intenta hacerlo con el teclado

**Comment by Alexfirer** [comment]
Resolví el problema de una forma un tanto graciosa XD,unicamebte debía
reinstalar el parche y ya estaba :3,gracias!

**Comment by Darkmet98** [comment]
Perfecto, es raro que por culpa del parche no te funcionara bien, pero bueno, la informática tambien tiene sus misterios xD
Cierro issue.
