### ISSUE TITLE
[texto/grafico japones] 2 caso

### ISSUE THREAD

**Issue by Alexfirer** [TranScene/Danganronpa-2#18]
En el caso dos, cuando mencionan que chico f tiene una hermana pequeña, sale una pequeña cinematica donde aparece esa escena del juego donde encuentra la nota en twilight..., el caso es que esta en japones, no se si sea a proposito o no, pero aqui lo reporto. link para la imagen:

https://drive.google.com/open?id=11AE1ZLzBOKPDZVExjkGoeSkigrSulGvz

**Comment by ghost** [comment]
Hola, no soy parte del proyecto, pero puedo responderte.
Sí. Es a propósito.
Cuando se referencia al juego en flashbacks siempren salen los textos en japonés, así esté puesto en inglés.

**Comment by Alexfirer** [comment]
Gracias, no sabia ese dato :D
