### ISSUE TITLE
¿volver al idioma original?

### ISSUE THREAD

**Issue by Goteromaxi** [TranScene/Danganronpa-2#19]
¿como podria volver a poner el idioma ingles si es que lo deseara?
la traduccion esta correcta y me parece muy buena pero estoy acostumbrado al juego en ingles desde danganronpa v3 ( no me puedo acostumbrar a ver el juego en español xd)

**Comment by Darkmet98** [comment]
Reinstalando el juego.
Cierro la issue

**Comment by joguersan** [comment]
No es necesario reinstalar el juego, puedes verificar la caché del mismo para que Steam elimine cualquier archivo modificado, de esta manera: https://support.sega.co.uk/hc/es/articles/201467152-Verificar-la-integridad-de-la-cach%C3%A9-del-juego

**Comment by Goteromaxi** [comment]
muchas gracias revisar el cache me funciono
