### ISSUE TITLE
Corrección en la conjugación

### ISSUE THREAD

**Issue by Fabricio2306** [TranScene/Danganronpa-2#2]
Buenas, estaba jugando los primeros momentos del tiempo libre y encontré este error de conjugación al hablar con Togami por primera vez. El verbo está mal conjugado, sugiero cambiarlo a **Estaba empezando** o bien solo **Empezaba**. Seguiré reportando si encuentro cualquier otro tipo de error y muchas gracias de antemano por el parche, les quedo genial :). PD: No se porque no me aparece la opción de agregar labels, pero creo que esta issues entraria en la categoria **Mejora**. 
Eso es todo, muchas gracias.
![issues 1](https://user-images.githubusercontent.com/21060691/33593345-08990890-d95d-11e7-9821-1a7cef7a28b4.png)

**Comment by joguersan** [comment]
Error corregido, procedo a cerrar la issue. ¡Muchas gracias por tu colaboración!
