### ISSUE TITLE
No puedo parchear

### ISSUE THREAD

**Issue by Madonchan** [TranScene/Danganronpa-2#20]
Siempre que se supone que terminara el parche me sale esto : 
![sin titulo](https://user-images.githubusercontent.com/35386219/34900889-45edd61c-f7da-11e7-823e-b85db0342c38.png)
Ya intente descargar lo de los links y hasta reiniciar . . . Muchas gracias de antemano 

-

**Comment by Darkmet98** [comment]
Has probado a ejecutar el parcheador en modo administrador?

**Comment by Madonchan** [comment]
Muchisimas gracias <3

**Comment by Darkmet98** [comment]
Me alegro de que te haya funcionado, cierro issue ^^.
