### ISSUE TITLE
No me deja Parchear en Mac

### ISSUE THREAD

**Issue by c0velo** [TranScene/Danganronpa-2#22]
Hola (y gracias por la traduccion) me he descargado el parche y me sale el archivo .wad y el "leeme". Mi Mac no me deja abrir el archivo para "parchear" pone en "leeme" que usemos la herramienta iZip (que no la comocia) la descargue y solo me lo descomprime. Lo he intentado de todas las maneras pero no me deja abrirlo. El juego lo compre en steam y lo tengo en mi cuenta. Pero no soy capaz de hacerlo. Una ayuda?

**Comment by Ferny148** [comment]
Yo tengo un problema similar pero el mio es que no medeja sellecionar el juego donde lo uso, lo pongo en una carpeta y le doy clic manualmente alli y me dice que el uego no se encuentra alli y no se que hacer ayuda

**Comment by joguersan** [comment]
Hemos comprobado la estructura del juego en Mac y Linux y hemos llegado a la conclusión de que el parche no es compatible con dichas versiones. Intentaremos trabajar en ello, pero mientras tanto tendréis que instalar el juego en una máquina virtual de Windows para poder aplicar el parche.

**Comment by matiasprad12** [comment]
hola tengo un error que me aparece al final de instalar el parche es algo de JIT Just-In-Timen sinceramente no lo entiendo
