### ISSUE TITLE
no se parchea

### ISSUE THREAD

**Issue by m0rris83** [TranScene/Danganronpa-2#24]
he intentado mucho , ejecutar el parchaear como administrador y todo va bien pero al momento eso me dice que ponga el parche manualmente y me voy al juego y ya se va instalando , el problema es que cuando lo abro desde steam me sigue saliendo le juego en ingles , y no me movido lo del mouse and keyboard , lo abri tambien desde los archivos donde esta el launcher y tambien me sigue saliendo en ingles ,¡que puedo hacer?

**Comment by joguersan** [comment]
¿Pero sale una alerta en el parcheador al final del proceso diciendo que el parcheo se ha realizado correctamente? Por favor, envía una captura del interior de la carpeta del juego.

**Comment by m0rris83** [comment]
ya lo arregle , desinstale steam , sospechaba que era algo asi pero ya esta arreglado 
![image](https://user-images.githubusercontent.com/37012975/36941798-8959465e-1f29-11e8-897b-65889266885c.png) hay esta otra vez pero esta vez si se puso en español

**Comment by joguersan** [comment]
Error resuelto, procedo a cerrar la issue.
