### ISSUE TITLE
Error en el parche al descargarse

### ISSUE THREAD

**Issue by SirM4ku** [TranScene/Danganronpa-2#25]
Bueno, antes de nada aclarar que el parche ya lo he iniciado como Administrador, e incluso desactivado el antivirus por si lo bloqueaba, configure y desactive el Firewall y tengo el .Net Framework hasta la ultima version (Windows 10 con todo y actualizaciones) pero al aprecer no me deja descargar el parche.

He aqui una imagen:
![image](https://user-images.githubusercontent.com/37784743/37881798-87194dea-3062-11e8-9a7e-ef25ce1f32d6.png)

**Comment by SirM4ku** [comment]
En fin, como solucion opte por descargar la version de Linux y parchearlo "Manualmente".
Así que supongo que el problema puede ser que el programa no se conecte al servidor donde descarga el parche.

> EDIT: Como le encontré solución a mi problema lo mas probable es que cierren el hilo, pero aun así creo que hay gente que puede estar teniendo el mismo problema y han intentado de varias formas arreglarlo, tan solo espero que arregléis este pequeño problema ya que sin ustedes los que trabajaron en este parche al español de este juego no podía haber sido posible, yo por mi parte les agradezco el haberlo hecho.

**Comment by joguersan** [comment]
Se trató de un error puntual del servidor, que se cayó. Cierro la issue
