### ISSUE TITLE
No me permite parchear

### ISSUE THREAD

**Issue by Litawaby** [TranScene/Danganronpa-2#26]
tal cual lo que se ve en pantalla y no le encuentro solución, no se que hacer
![li](https://user-images.githubusercontent.com/38384030/38771190-3118ee64-3fe4-11e8-8bd8-1b7443b036a5.jpg)

![lii](https://user-images.githubusercontent.com/38384030/38771188-2b93bc08-3fe4-11e8-90e8-047ba96fb231.jpg)

**Comment by joguersan** [comment]
¿Has descargado la última versión del parcheador? Lo que te ocurre es un bug de la primera versión que lanzamos hace más de 4 meses.
https://github.com/TranScene/Danganronpa-2/releases/tag/1.1

**Comment by Litawaby** [comment]
si, y me aparece siempre lo mismo :/

**Comment by Darkmet98** [comment]
@Litawaby ¿puedes mandar una captura mostrando los archivos de la ruta donde tienes instalado Danganronpa 2?

**Comment by Darkmet98** [comment]
Ha pasado una semana y no ha respondido el autor, cierro issue.
