### ISSUE TITLE
Error al descargar el parche!

### ISSUE THREAD

**Issue by nonstop1002** [TranScene/Danganronpa-2#27]
Cada vez que intento descargar el parche me sale este mensaje.
![help](https://user-images.githubusercontent.com/38666582/39142493-39afa26a-4701-11e8-888f-e9fcdd60f0e4.png)

ayuda! :(

**Comment by Darkmet98** [comment]
¿Has ejecutado en modo administrador el parcheador?

**Comment by nonstop1002** [comment]
Ya lo hice. Pero ahora cada vez que le doy a "Launch" en el Launcher, el juego no se abre.

**Comment by Darkmet98** [comment]
Que raro...
¿Antes funcionaba?

**Comment by nightmare456** [comment]
tengo el mismo problema, tengo el parche de administrador pero sigue sin funcionar, que podrá ser?

**Comment by darkmind03** [comment]
yo tengo el mismo error, alguien sabe como arreglarlo?

**Comment by joguersan** [comment]
Volved a descargar el parcheador. Mudamos todos nuestros parches a la web de TraduSquare y el parcheador intentaba descargarlo de donde no era.

**Comment by darkmind03** [comment]
Gracias, ahora ya funciona bien, y les agradezco por el parche, hicieron un
gran trabajo

**Comment by joguersan** [comment]
Problema resuelto. Cierro la issue
