### ISSUE TITLE
¡Error al intentar instalar el Parche!

### ISSUE THREAD

**Issue by Santi33** [TranScene/Danganronpa-2#28]
¡Buenas noches! Hoy he visto que el juego estaba en oferta y decidí comprármelo por Steam. Primero abrí el Parche y decía que se iba a instalar, pero me aparecía un error al segundo el cual, buscando en internet, descubrí como se solucionaba. Al intentarlo (ejecutando como administrador) decía que el juego no estaba instalado en la carpeta que elegí, cuando anteriormente sí me dejaba. ¿Por qué pasa esto? ¿Podrían ayudarme? Muchas gracias y pasen buena noche.

**Comment by Santi33** [comment]
Instalé y desinstalé en juego para que se crease una nueva carpeta, y esta si la detectó, pero me sale el error de Microsoft .NET Framework, y eso que lo abrí con administrador. ¿Qué hago?

**Comment by Santi33** [comment]
Y ahora no me detecta el juego de nuevo. No entiendo nada, ayuda, por favor.

**Comment by Santi33** [comment]
¡Ya lo solucioné! Tuve que desinstalar Steam y volverlo a instalar. ¡Muchas gracias por éste magnífico trabajo!

**Comment by joguersan** [comment]
Problema solucionado. Cierro la issue
