### ISSUE TITLE
Tengo un error con el Parche en español

### ISSUE THREAD

**Issue by Nicool2201** [TranScene/Danganronpa-2#29]
Tengo un error que dice:
Error no controlada en la aplicación. Si hace clic en continuar,
la aplicación omitirá este error y intentara continuar. Si hace clic en salir, la
aplicación se cerrara automáticamente.
La cadena de entrada no tiene formato correcto

Y luego cuando lo intento otra vez o presiono continuar sale otro que dice que falta un archivo
dr2_data_keyword.wad

Tengo el juego original y no se que pasa Ayuda!!
![2018-07-03 2](https://user-images.githubusercontent.com/40815339/42256632-0cb5da64-7f18-11e8-98af-83ca4de8cd73.png)
![captura](https://user-images.githubusercontent.com/40815339/42258955-e855666a-7f23-11e8-9329-60a1bfb594d0.PNG)

**Comment by GabuTsuki** [comment]
Me pasa exactamente lo mismo :c arreglenlo pronto, por favor

**Comment by joguersan** [comment]
Mete el parcheador en una carpeta como Mis Documentos o C:/ y ejecútalo como administrador

**Comment by joguersan** [comment]
Al no haber recibido respuesta, procedo a cerrar la issue
