### ISSUE TITLE
Primer juicio - Términos

### ISSUE THREAD

**Issue by Fabricio2306** [TranScene/Danganronpa-2#3]
Hola, bueno no creo que sean errores, más bien son cosillas que se pasaron desapercibidas. Bien, para empezar cuando en los textgreen que te explican como jugar, define el termino "DFC" como duelo de fuego cruzado, sin embargo, la letra P no coincide con la "D" de Duelo. sugiero cambiarlo por la D para evitar confusiones xD. 
![issues 2](https://user-images.githubusercontent.com/21060691/33684176-60607b82-da9b-11e7-8011-5a811c66688d.png)

Asimismo, cuando continua con la explicación, no se ha cambiado el término PTA por DFC ya que el primero viene de las siglas en ingles del modo de juego y pienso que se les paso cambiar esa parte (suele pasar :v). Sugiero también cambiarlo por DFC para evitar confusiones a los que recién empiezan a jugar, o bien dejarlo así y cambiar el DFC por PTA ... pero creo que seria mucho eso ya que tmb tendrian que cambiar todo...mejor lo primero v: .

![issues 3](https://user-images.githubusercontent.com/21060691/33684439-3f5d1ce6-da9c-11e7-923b-a70e19940fd9.png)

Bueno hasta aquí mi reporte! 👍 
Gracias.

PD: todavía no me aparece las opciones de labels asi que en adelante dejare la referencia de label para que los coloquen:
**Label: mejora**

**Comment by joguersan** [comment]
Errores corregidos, procedo a cerrar la issue. ¡Muchas gracias por tu colaboración!
