### ISSUE TITLE
error al parchear 

### ISSUE THREAD

**Issue by elmontix** [TranScene/Danganronpa-2#33]
al intentar parchear como administrador me aparece este error 
![unnamed](https://user-images.githubusercontent.com/57310238/68086682-00af9080-fe2d-11e9-9a27-34d569b22b39.jpg)

**Comment by PinguinitoUwU** [comment]
me pasa lo mismo ami. nunca me deja descargar y me dice que no existe un archivo llamado keyboard pero cuando busco en la carpeta de danganronpa 2 aparece. ayudenme pls :(

**Comment by julietaZorrilla** [comment]
Me pasa exactamente lo mismo

**Comment by elmontix** [comment]
Llegue a la conclusión de que el juego se actualizo y por eso el parche de traducción ya no aplica. Aunque intente descargar versiones anteriores del juego pero aun así no pude traducirlo. Y los de TranScene dejaron tirado su parche sin seguir actualizándolo ni controlandolo.

**Comment by PinguinitoUwU** [comment]
f......
 aun asi ya voy por el 3 :v

**Comment by joguersan** [comment]
La traducción no funciona porque estáis siguiendo páginas que no son la ficha oficial del juego. Si os descargáis el parche desde https://tradusquare.es/ficha.php?danganronpa-2 podréis instalarlo sin problema.
El enlace que lleva a este github está obsoleto porque el parcheador dejó de funcionar cuando cambiamos de página web al no poder descargar los datos de la antigua. Cierro la issue e intentaré eliminar todo rastro del parcheador por ahora.

**Comment by elmontix** [comment]
ahora me aparece este problema 
![Sin título](https://user-images.githubusercontent.com/57310238/70002755-ca565580-153f-11ea-9733-745189c1eff7.png)

**Comment by elmontix** [comment]
Gracias!
