### ISSUE TITLE
Primer Juicio - Error de encuadre de texto

### ISSUE THREAD

**Issue by Fabricio2306** [TranScene/Danganronpa-2#4]
Ocurre un error de encuadre del texto en los green text. la ultima oración aparece fuera del encuadre del dialogo y no se llega a ver. Esto ocurre al momento de explicar sobre el DFC - Primer jucio. solo sucede alli, lo demás esta bien.
![issues 4](https://user-images.githubusercontent.com/21060691/33684883-cab5ac62-da9d-11e7-9f1e-2b44761b975e.png)

**Label: Fallo texto**

**Comment by joguersan** [comment]
Errores corregidos, procedo a cerrar la issue. ¡Muchas gracias por tu colaboración!
