### ISSUE TITLE
Una letra erronea

### ISSUE THREAD

**Issue by Ryumizaki** [TranScene/Danganronpa-2#5]
Durante el primer juicio (casi al final) me encontré que en la explicación de duelo de fuego cruzado hay una P antes de duelo para luego poner DFC así que creó que la P debería ser una D
![danganronpa 2 _ goodbye despair 06_12_2017 11_32_02 p m](https://user-images.githubusercontent.com/34330449/33700546-81966be2-dadf-11e7-8b8e-f04688cbe842.png)

**Comment by Ryumizaki** [comment]
Lastima que llego tarde, acabo de ver que alguien se me adelanto, eso pasa por estar en ka universidad en vez de estar jugando, como aportación puede que el error sea porque se tradujo como pelea y duelo al mismo tiempo pero no se como era en ingles así que no estoy seguro.

**Comment by Darkmet98** [comment]
Tal y como dices, está referenciado en #3 .Voy a cerrar el issue, muchisimas gracias por tu contribución.
