### ISSUE TITLE
Posible redundancia y palabra mal escrita??

### ISSUE THREAD

**Issue by Fabricio2306** [TranScene/Danganronpa-2#6]
Buenas, avanzando con el juego me encontré con esta frase curiosa que describe el armario de la casa de playa de la segunda isla. La frase "casi parece un armario que usan de armario" suena algo redundante. Pero no estoy seguro si es que sea un error, ya que a mi parecer la idea del traductor era de expresar que ese armario es más grande que un armario común y la frase utilizada denota exageración.
![issues 2](https://user-images.githubusercontent.com/21060691/33799486-d27ed680-dcfa-11e7-8ac2-5debedc1cb30.png)

Y con respecto a esta palabra..."Escuchándoos"...definitivamente pensaba que era un error pero al revisar en san google xD, me sorprendí que si existía esa palabra. por esa razón, tampoco estoy seguro de que sea un error. Para mi suena mejor "escuchándolos" pero ya se los dejo a su criterio. **Esta parte se encuentra cuando visitas por primera vez la biblioteca de la segunda isla**.
![issues 3](https://user-images.githubusercontent.com/21060691/33799522-a210324a-dcfb-11e7-994f-282768a6c5a2.png)

Como no estoy seguro de que ambos sean errores, lo dejaré como una duda que tengo.

**Label: duda**

**Comment by joguersan** [comment]
Errores corregidos. Efectivamente, el segundo está bien escrito, es la forma de plural en español de España. Procedo a cerrar la issue. ¡Muchas gracias por tu colaboración!
