### ISSUE TITLE
Nihilismo (SPOILERS)

### ISSUE THREAD

**Issue by legendaryX77** [TranScene/Danganronpa-2#7]
Aviso que no estoy seguro de si esto se podría considerar un error.
En el último caso, cuando estás en cierto debate continuo (no digo detalles para no hacer spoiler a cualquiera que lea esto) tienes una bala que tiene la palabra "nihilismo". Bien, en la versión original del juego, ponía "nihil" que significa en latín "nada", porque es eso: no puedes presentar nada. Nihilismo es más bien una corriente filosófica que cree que la vida no tiene un sentido, lo cual no tiene por qué ser necesariamente malo.

Por lo tanto, creo que sería mejor dejar esa bala como "nihil"

**Comment by joguersan** [comment]
Efectivamente, el nihilismo es una corriente filosófica, pero también es esto que viene aquí:
![image](https://user-images.githubusercontent.com/9279554/34018276-6db44fcc-e129-11e7-82b8-cb63630a30b0.png)

Se aplica al significado de esa munición, por lo tanto cierro esta issue.
