### ISSUE TITLE
Correcciones de palabras - Capitulo 2

### ISSUE THREAD

**Issue by Fabricio2306** [TranScene/Danganronpa-2#8]
Hola, adjunto algunos errores que encontré en el capitulo 2

1. Separar estas palabras "metíen" -> metí en. **encontrado en el segundo teatro monokuma del 
    capitulo 2**

![issues 1](https://user-images.githubusercontent.com/21060691/34061581-d7a65b36-e1b6-11e7-8da8-0245c6bd9f71.png)

2. Separar palabras "medila" -> me di la. **encontrado antes de que nanami entrará a la cafetería de la segunda isla**

![issues 2](https://user-images.githubusercontent.com/21060691/34061640-1c03bc24-e1b7-11e7-96eb-4a2bc7c2a629.png)

3. Cambiar palabra "deber" por "debió".**encontrado al jugar _twilight sindrome_ - primer día, cuando encuentran el cuerpo.**

![issues 3](https://user-images.githubusercontent.com/21060691/34061758-9a621cfa-e1b7-11e7-844f-d93ad148974e.png)

4. Separar "queéramos" -> que éramos.**encontrado en las palabras de kuzuryu antes de que ejecuten al culpable del segundo asesinato :'v**
![issues 6](https://user-images.githubusercontent.com/21060691/34061924-1bc8b132-e1b8-11e7-8909-e83c425d0cf5.png)

Eso es todo

**Label: mejora**

**Comment by joguersan** [comment]
Errores corregidos, procedo a cerrar la issue. ¡Muchas gracias por tu colaboración!
